### ISSUE TITLE
NullPointerException in biodata-tools

### ISSUE THREAD

**Issue by mbsimonovic** [opencb/biodata#89]
develop branch (latest commit _27c7edb_) build breaks with NPE:

`Running org.opencb.biodata.tools.variant.converter.VariantContextToVariantConverterTest
Error writing batch 1
org.apache.avro.file.DataFileWriter$AppendWriteException: java.lang.NullPointerException: null of org.opencb.biodata.models.variant.avro.VariantType in field type of org.opencb.biodata.models.variant.avro.AlternateCoordinate of array of union in field secondaryAlternates of org.opencb.biodata.models.variant.avro.StudyEntry of array in field studies of org.opencb.biodata.models.variant.avro.VariantAvro
	at org.apache.avro.file.DataFileWriter.append(DataFileWriter.java:296)
	at org.opencb.biodata.tools.variant.converter.VariantContextToVariantConverterTest.lambda$writeFile$8(VariantContextToVariantConverterTest.java:199)
	at org.opencb.biodata.tools.variant.converter.VariantContextToVariantConverterTest$$Lambda$14/884452399.write(Unknown Source)
	at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.run(ParallelTaskRunner.java:458)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null of org.opencb.biodata.models.variant.avro.VariantType in field type of org.opencb.biodata.models.variant.avro.AlternateCoordinate of array of union in field secondaryAlternates of org.opencb.biodata.models.variant.avro.StudyEntry of array in field studies of org.opencb.biodata.models.variant.avro.VariantAvro
	at org.apache.avro.generic.GenericDatumWriter.npe(GenericDatumWriter.java:93)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:87)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:58)
	at org.apache.avro.file.DataFileWriter.append(DataFileWriter.java:290)
	... 8 more
Caused by: java.lang.NullPointerException
	at org.apache.avro.generic.GenericDatumWriter.writeEnum(GenericDatumWriter.java:124)
	at org.apache.avro.specific.SpecificDatumWriter.writeEnum(SpecificDatumWriter.java:57)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:67)
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:114)
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:104)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:66)
	at org.apache.avro.generic.GenericDatumWriter.writeArray(GenericDatumWriter.java:138)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:68)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:114)
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:104)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:66)
	at org.apache.avro.generic.GenericDatumWriter.writeArray(GenericDatumWriter.java:138)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:68)
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:114)
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:104)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:66)
	... 10 more
Abort writing thread on fail
Abort task thread on fail
Abort task thread on fail
Abort task thread on fail
Abort task thread on fail
Abort task thread on fail
read:  timeReading                  = 0.41486584s
read:  timeBlockedAtPutRead         = 9.05127E-4s
task;  timeBlockedAtTakeRead        = 9623448.96749982s
task;  timeTaskApply                = 1.595751404s
task;  timeBlockedAtPutWrite        = 7.7235E-5s
write: timeBlockedWatingDataToWrite = 0.290468599s
write: timeWriting                  = 0.07554789s
total:                              = 0.51255458s
Error writing batch 1
org.apache.avro.file.DataFileWriter$AppendWriteException: java.lang.NullPointerException: null of org.opencb.biodata.models.variant.avro.VariantType in field type of org.opencb.biodata.models.variant.avro.AlternateCoordinate of array of union in field secondaryAlternates of org.opencb.biodata.models.variant.avro.StudyEntry of array in field studies of org.opencb.biodata.models.variant.avro.VariantAvro
	at org.apache.avro.file.DataFileWriter.append(DataFileWriter.java:296)
	at org.opencb.biodata.tools.variant.converter.VariantContextToVariantConverterTest.lambda$writeFile$8(VariantContextToVariantConverterTest.java:199)
	at org.opencb.biodata.tools.variant.converter.VariantContextToVariantConverterTest$$Lambda$14/884452399.write(Unknown Source)
	at org.opencb.commons.run.ParallelTaskRunner$WriterRunnable.run(ParallelTaskRunner.java:458)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null of org.opencb.biodata.models.variant.avro.VariantType in field type of org.opencb.biodata.models.variant.avro.AlternateCoordinate of array of union in field secondaryAlternates of org.opencb.biodata.models.variant.avro.StudyEntry of array in field studies of org.opencb.biodata.models.variant.avro.VariantAvro
	at org.apache.avro.generic.GenericDatumWriter.npe(GenericDatumWriter.java:93)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:87)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:58)
	at org.apache.avro.file.DataFileWriter.append(DataFileWriter.java:290)
	... 8 more
Caused by: java.lang.NullPointerException
	at org.apache.avro.generic.GenericDatumWriter.writeEnum(GenericDatumWriter.java:124)
	at org.apache.avro.specific.SpecificDatumWriter.writeEnum(SpecificDatumWriter.java:57)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:67)
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:114)
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:104)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:66)
	at org.apache.avro.generic.GenericDatumWriter.writeArray(GenericDatumWriter.java:138)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:68)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:114)
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:104)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:66)
	at org.apache.avro.generic.GenericDatumWriter.writeArray(GenericDatumWriter.java:138)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:68)
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:114)
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:104)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:66)
	... 10 more
`

**Comment by j-coll** [comment]
Thanks for reporting!

This bug is solved at [a6bdc85](https://github.com/opencb/biodata/commit/a6bdc85)
